# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-18 15:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas', '0002_auto_20181218_0944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ninja',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='ninja',
            name='updated_at',
        ),
    ]
