# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-18 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas', '0005_dojo_ninja'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='desc',
            field=models.TextField(default='Dojo Desc'),
        ),
    ]
